apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examplevalues.tools.opdev.io
spec:
  group: tools.opdev.io
  names:
    kind: ExampleValues
    plural: examplevalues
    singular: examplevalues
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Defines the desired state of Example Values
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Defines the status of Example Values
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
