---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 261fb2ec0e3d3ba3f4fad67e3ecee629d1de87ae
    app.quarkus.io/build-timestamp: 2023-07-24 - 17:37:12 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: java-helm-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: java-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-helm-operator
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 261fb2ec0e3d3ba3f4fad67e3ecee629d1de87ae
        app.quarkus.io/build-timestamp: 2023-07-24 - 17:37:12 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: java-helm-operator
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/opdev/java-helm-operator-controller:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: java-helm-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: java-helm-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examplevaluesreconciler-cluster-role
rules:
  - apiGroups:
      - tools.opdev.io
    resources:
      - examplevalues
      - examplevalues/status
      - examplevalues/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examplevaluesreconciler-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: examplevaluesreconciler-cluster-role
subjects:
  - kind: ServiceAccount
    name: java-helm-operator
    namespace: helmtest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: examplevaluesreconciler-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: java-helm-operator
    namespace: helmtest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 261fb2ec0e3d3ba3f4fad67e3ecee629d1de87ae
    app.quarkus.io/build-timestamp: 2023-07-24 - 17:37:12 +0000
  labels:
    app.kubernetes.io/name: java-helm-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: java-helm-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: java-helm-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: java-helm-operator
    namespace: helmtest
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 261fb2ec0e3d3ba3f4fad67e3ecee629d1de87ae
    app.quarkus.io/build-timestamp: 2023-07-24 - 17:37:12 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: java-helm-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: java-helm-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: java-helm-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
